import React from "react";
import "./footer.scss";
const footer = () => {
    return (
        <>
            <footer>
                <ul className="footer-links flex">
                    <li>
                        <a
                            href="https://about.meta.com/"
                            target="_blank"
                            rel="noreferrer"
                        >
                            Meta
                        </a>
                    </li>
                    <li>
                        <a
                            href="https://about.instagram.com/"
                            target="_blank"
                            rel="noreferrer"
                        >
                            About
                        </a>
                    </li>
                    <li>
                        <a
                            href="https://about.instagram.com/"
                            target="_blank"
                            rel="noreferrer"
                        >
                            Blogs
                        </a>
                    </li>
                    <li>
                        <a
                            href="https://about.instagram.com/about-us/careers"
                            rel="noreferrer"
                            target="_blank"
                        >
                            Jobs
                        </a>
                    </li>
                    <li>
                        <a
                            href="https://help.instagram.com/"
                            target="_blank"
                            rel="noreferrer"
                        >
                            Help
                        </a>
                    </li>
                    <li>
                        <a
                            href="https://developers.facebook.com/docs/instagram"
                            target="_blank"
                            rel="noreferrer"
                        >
                            API
                        </a>
                    </li>
                    <li>
                        <a
                            href="https://privacycenter.instagram.com/policy/?entry_point=ig_help_center_data_policy_redirect"
                            target="_blank"
                            rel="noreferrer"
                        >
                            Privacy
                        </a>
                    </li>
                    <li>
                        <a
                            href="https://help.instagram.com/581066165581870/"
                            target="_blank"
                            rel="noreferrer"
                        >
                            Terms
                        </a>
                    </li>
                    <li>
                        <a
                            href="https://www.instagram.com/accounts/login/?next=%2Fdirectory%2Fprofiles%2F"
                            target="_blank"
                            rel="noreferrer"
                        >
                            Top accounts
                        </a>
                    </li>
                    <li>
                        <a
                            href="https://www.instagram.com/explore/locations/"
                            target="_blank"
                            rel="noreferrer"
                        >
                            Locations
                        </a>
                    </li>
                    <li>
                        <a
                            href="https://www.instagram.com/web/lite/"
                            target="_blank"
                            rel="noreferrer"
                        >
                            Instagram Lite
                        </a>
                    </li>
                    <li>
                        <a
                            href="https://www.instagram.com/web/lite/"
                            target="_blank"
                            rel="noreferrer"
                        >
                            Contact uploading and no-users
                        </a>
                    </li>
                    <li>
                        <a
                            href="https://www.instagram.com/web/lite/"
                            target="_blank"
                            rel="noreferrer"
                        >
                            English (UK)
                        </a>
                    </li>
                    <li>
                        <a
                            href="https://www.instagram.com/web/lite/"
                            target="_blank"
                            rel="noreferrer"
                        >
                            © 2023 Instagram from Meta
                        </a>
                    </li>
                </ul>
            </footer>
        </>
    );
};

export default footer;
